version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - .:/var/www/html/
    ports:
      - 80:80
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: booking
      MYSQL_USER: yeongmi
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"